### ISSUE TITLE
KeyError: 'set-cookie'

### ISSUE THREAD

**Issue by suvidhpawar** [Sid72020123/scratchconnect#49]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    login = scratchconnect.ScratchConnect("username", "password")
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/scratchconnect/ScratchConnect.py", line 37, in __init__
    self._login(cookie=False, auto_cookie_login=self.auto_cookie_login)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/scratchconnect/ScratchConnect.py", line 94, in _login
    self.session_id = re.search('"(.*)"', request.headers["Set-Cookie"]).group()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'
  

please note this is a shared project https://scratch.mit.edu/projects/649081138/editor
the username and password are correct 
and there is no syntax mistake
the python version is 3.1
it's a relpit server (link: https://replit.com/@suvidhpawar/scratch-violet-os-sever#main.py)
and I don't know something else

**Comment by Sid72020123** [comment]
Actually due to the Scratch API's ban on replit, you cannot use or request the Scratch API in replit. So, the code won't work. I am working on making the library work on replit.

**Comment by suvidhpawar** [comment]
Will it work on pycharm  ?

**Comment by suvidhpawar** [comment]
its giving a different error on my pc in PyCharm
is it banned here too

Traceback (most recent call last):
  File "/Users/. /  / /main.py", line 12, in <module>
    variables = project.connect_cloud_variables()
  File "/Users//venv/lib/python3.10/site-packages/scratchconnect/Project.py", line 490, in connect_cloud_variables
    return CloudConnection.CloudConnection(project_id=self.project_id, client_username=self.client_username,
  File "/Users//venv/lib/python3.10/site-packages/scratchconnect/CloudConnection.py", line 58, in __init__
    self._make_connection()
  File "//venv/lib/python3.10/site-packages/scratchconnect/CloudConnection.py", line 126, in _make_connection
    self._ws.connect(
  File "//venv/lib/python3.10/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/venv/lib/python3.10/site-packages/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "//venv/lib/python3.10/site-packages/websocket/_http.py", line 271, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "//venv/lib/python3.10/site-packages/websocket/_http.py", line 247, in _wrap_sni_socket
    return context.wrap_socket(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)
