### ISSUE TITLE
Online IDE Login Error

### ISSUE THREAD

**Issue by 1and1is3** [Sid72020123/scratchconnect#56]
As i try to login on Replit i get the error:
`Traceback (most recent call last):
  File "/home/runner/scratchatgpt2/venv/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    user = scratchconnect.ScratchConnect(online_ide_cookie=scratch_cookie)
  File "/home/runner/scratchatgpt2/venv/lib/python3.10/site-packages/scratchconnect/ScratchConnect.py", line 75, in __init__
    super().__init__(self.username,
  File "/home/runner/scratchatgpt2/venv/lib/python3.10/site-packages/scratchconnect/UserCommon.py", line 27, in __init__
    self.update_data()
  File "/home/runner/scratchatgpt2/venv/lib/python3.10/site-packages/scratchconnect/UserCommon.py", line 53, in update_data
    data = requests.get(f"{self._user_link}").json()
  File "/home/runner/scratchatgpt2/venv/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)`

**Comment by Sid72020123** [comment]
I'm really very sorry. I forgot to announce that the `Online IDE login` feature uses a proxy hosted on [deta.sh](https://deta.sh/) which is going to shut down on _1st of May, 2023_. I will update the proxy and host/deploy it on [deta.space](https://deta.space/).

I'm surely going to update the library and fix the error before the last week of this month.

I will release a new version to fix that in a few days. Sorry.

**Comment by 1and1is3** [comment]
Thanks for reacting so fast. Good you can solve the problem. 
[programORdie](https://scratch.mit.edu/users/programORdie/)

**Comment by Sid72020123** [comment]
> Thanks for reacting so fast. Good you can solve the problem. [programORdie](https://scratch.mit.edu/users/programORdie/)

You're welcome.

I will try to fix the problem as soon as possible.

**Comment by RetrogradeDev** [comment]
Sorry, but i still get the same error.

**Comment by RetrogradeDev** [comment]
Oh, sorry, it works, Replit just hadn't updated the package yet.
