### ISSUE TITLE
IDE Cloud Error

### ISSUE THREAD

**Issue by RetrogradeDev** [Sid72020123/scratchconnect#57]
Traceback (most recent call last):
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/scratchatgpt/venv/lib/python3.10/site-packages/scratchconnect/CloudConnection.py", line 110, in _ping_task
    self._ws.pong()
  File "/home/runner/scratchatgpt/venv/lib/python3.10/site-packages/websocket/_core.py", line 351, in pong
    self.send(payload, ABNF.OPCODE_PONG)
  File "/home/runner/scratchatgpt/venv/lib/python3.10/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
  File "/home/runner/scratchatgpt/venv/lib/python3.10/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
  File "/home/runner/scratchatgpt/venv/lib/python3.10/site-packages/websocket/_core.py", line 525, in _send
    return send(self.sock, data)
  File "/home/runner/scratchatgpt/venv/lib/python3.10/site-packages/websocket/_socket.py", line 170, in send
    return _send()
  File "/home/runner/scratchatgpt/venv/lib/python3.10/site-packages/websocket/_socket.py", line 147, in _send
    return sock.send(data)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

**Comment by Sid72020123** [comment]
Oh. That error was already known and it occurred due to the error in Scratch servers. Try to update your session ID in the environment variables of replit (in case you use it) and run the program again...

**Comment by RetrogradeDev** [comment]
ok, thanks.
