### ISSUE TITLE
scratchconnect import issue???

### ISSUE THREAD

**Issue by boredistan** [Sid72020123/scratchconnect#58]
Exception has occurred: TypeError
'type' object is not subscriptable
  File "/home/musa/Desktop/scratchautomation.py", line 1, in <module>
    import scratchconnect
TypeError: 'type' object is not subscriptable

**Comment by boredistan** [comment]
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> import scratchconnect
[1m[33mScratchConnect[32m[3m v5.0[37m -[36m https://sid72020123.github.io/scratchconnect/[0m
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#0>", line 1, in <module>
  File "/home/musa/.local/lib/python3.8/site-packages/scratchconnect/__init__.py", line 26, in <module>
    from scratchconnect.ScratchConnect import ScratchConnect
  File "/home/musa/.local/lib/python3.8/site-packages/scratchconnect/ScratchConnect.py", line 13, in <module>
    from scratchconnect import Project
  File "/home/musa/.local/lib/python3.8/site-packages/scratchconnect/Project.py", line 10, in <module>
    from scratchconnect import CloudConnection
  File "/home/musa/.local/lib/python3.8/site-packages/scratchconnect/CloudConnection.py", line 22, in <module>
    class CloudConnection:
  File "/home/musa/.local/lib/python3.8/site-packages/scratchconnect/CloudConnection.py", line 58, in CloudConnection
    def get_variable_data(self, limit: int = 100, offset: int = 0) -> list[dict]:
TypeError: 'type' object is not subscriptable

**Comment by Sid72020123** [comment]
Can you share me the full code here? Seems like there is a problem in your code...

Remove the sensitive information such as username and password from  your code and share it here.

**Comment by Sid72020123** [comment]
Also, uninstall the `v5.0` of the library and install the `v4.5.1` using `pip install scratchconnect==4.5.1` and then try again! Note: In `v4.5.1`, the online IDE feature will not work!

I will try to find all the errors and fix them in the next versions...

**Comment by RetrogradeDev** [comment]
I got the same error ...

**Comment by Sid72020123** [comment]
Sorry. I actually developed the new version in Python 3.10 which supports "|" for Union typing but the lower Python versions doesn't :(

I will fix that soon but I don't have the time to do that :/

**Comment by RetrogradeDev** [comment]
Maybe i can help? If you tell me what to do, I'll fix it.

**Comment by TheCommCraft** [comment]
You can try to update your python version @boredistan

**Comment by RetrogradeDev** [comment]
@TheCommCraft I use replit.

**Comment by TheCommCraft** [comment]
You can try to update your python version @boredistan
